{{- if .Values.rollout.blueGreenEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-info-service.fullname" . }}-preview
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "devops-info-service.selectorLabels" . | nindent 4 }}
{{- end }}
