apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-service-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Aleksandr-Isupov/Aleksandr-Isupov-DevOps-Core-Course.git
    targetRevision: HEAD
    path: k8s/helm/devops-info-service
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # Note: No automated sync policy for production
  # Manual sync required for controlled deployments
